# Generated by Django 4.2 on 2023-05-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_imagepost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='text',
        ),
    ]
