# Generated by Django 4.2 on 2023-05-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='expertise',
            name='image',
            field=models.ImageField(null=True, upload_to='expertise/'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='image_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='expertise',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
