# Generated by Django 4.2 on 2023-05-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_expertise_title_expertise_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hour',
            field=models.JSONField(default={'Friday': '', 'Monday': '', 'Saturday': '', 'Sunday': '', 'Thursday': '', 'Tuesday': '', 'Wednesday': ''}),
        ),
    ]
