# Generated by Django 4.2 on 2023-05-21 22:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_working_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='working_hour',
            field=models.JSONField(default=accounts.models.default_working_hours),
        ),
    ]
