# Generated by Django 4.2 on 2023-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rokhinfo',
            name='score',
            field=models.FloatField(default=4.7, max_length=3),
        ),
        migrations.AddField(
            model_name='rokhinfo',
            name='services',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='rokhinfo',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
