# Generated by Django 4.2 on 2023-05-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactus_ticketanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HanousaInfo',
            new_name='RokhInfo',
        ),
    ]
